//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinguaBraille.Content {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GameText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameText() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LinguaBraille.Content.GameText", typeof(GameText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous allez entendre un caractère, puis vous devrez taper le symbole correspondant sur votre plage Braille.
        ///Attention ! Vous n’avez qu’un seul essai !.
        /// </summary>
        internal static string Basic_practice_tips {
            get {
                return ResourceManager.GetString("Basic_practice_tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Frappe-tappe {0}.
        /// </summary>
        internal static string Basic_practice_title {
            get {
                return ResourceManager.GetString("Basic_practice_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Table braille {0}.
        /// </summary>
        internal static string Braille_tableview_title {
            get {
                return ResourceManager.GetString("Braille_tableview_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cet entraînement est le plus facile.
        ///Vous allez entendre un caractère, puis 4 signes Braille seront affichés.
        ///Vous devrez choisir lequel correspond en appuyant sur les chiffres de 1-4.
        ///Pour réécouter le signe, appuyez sur 0..
        /// </summary>
        internal static string Choice_practice_tips {
            get {
                return ResourceManager.GetString("Choice_practice_tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choix multiple {0}.
        /// </summary>
        internal static string Choice_practice_title {
            get {
                return ResourceManager.GetString("Choice_practice_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commencer !.
        /// </summary>
        internal static string First_screen_start {
            get {
                return ResourceManager.GetString("First_screen_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bienvenue.
        /// </summary>
        internal static string First_screen_title {
            get {
                return ResourceManager.GetString("First_screen_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entraînement : Frapp-tappe.
        /// </summary>
        internal static string Main_menu_basicpractice {
            get {
                return ResourceManager.GetString("Main_menu_basicpractice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entraînement : choix multiple.
        /// </summary>
        internal static string Main_menu_choice {
            get {
                return ResourceManager.GetString("Main_menu_choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Il n&apos;y a pas de mise à jour disponible..
        /// </summary>
        internal static string Main_menu_no_update {
            get {
                return ResourceManager.GetString("Main_menu_no_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paramètres.
        /// </summary>
        internal static string Main_menu_settings {
            get {
                return ResourceManager.GetString("Main_menu_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Découvrir la table Braille.
        /// </summary>
        internal static string Main_menu_table {
            get {
                return ResourceManager.GetString("Main_menu_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Relire les explications.
        /// </summary>
        internal static string Main_menu_tips {
            get {
                return ResourceManager.GetString("Main_menu_tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Menu principal.
        /// </summary>
        internal static string Main_menu_title {
            get {
                return ResourceManager.GetString("Main_menu_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une nouvelle mise à jour est disponible : {0}.
        /// </summary>
        internal static string Main_menu_update_available {
            get {
                return ResourceManager.GetString("Main_menu_update_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Télécharger la dernière mise à jour..
        /// </summary>
        internal static string Main_menu_update_download {
            get {
                return ResourceManager.GetString("Main_menu_update_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à En savoir plus sur le Braille Japonais.
        /// </summary>
        internal static string Main_menu_wiki {
            get {
                return ResourceManager.GetString("Main_menu_wiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entraînement : Écriture de mots.
        /// </summary>
        internal static string Main_menu_word_practice {
            get {
                return ResourceManager.GetString("Main_menu_word_practice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quitter.
        /// </summary>
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Score : {0}.
        /// </summary>
        internal static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Passage en mode saisie plage Braille..
        /// </summary>
        internal static string SDFJKL_Disabled {
            get {
                return ResourceManager.GetString("SDFJKL_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Passage en mode saisie SDFJKL..
        /// </summary>
        internal static string SDFJKL_Enabled {
            get {
                return ResourceManager.GetString("SDFJKL_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bienvenue dans cette version beta!
        ///Ce jeu à pour but de vous faire découvrir et pratiquer le Braille japonais. 
        ///Pour cela, vous aurez besoin d’utiliser une plage Braille, ainsi qu’un lecteur d’écran la supportant configuré pour utilisé la table braille française unifiée à 8 points. 
        ///Voici un aperçu des commandes qui vous seront utiles :
        ///Les flèches vous serve à naviguer dans les menus, entrée à sélectionner, échappe à quitter.
        ///F2 et F3 servent à ajuster le volume de la musique.
        ///Vous pouvez relire ces  [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }
    }
}
